/*

 BACKGROUNDONE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : H:\PROGRAMMING FILES\_Github\gb-fathers-day\imgs\backgrounds.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define background_1Width 40
#define background_1Height 18
#define background_1Bank 0

extern unsigned char background_1[];

/* End of BACKGROUNDONE.H */
