/*

 BACKGROUNDTHREE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : H:\PROGRAMMING FILES\_Github\gb-fathers-day\imgs\backgrounds.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define background_3Width 20
#define background_3Height 18
#define background_3Bank 0

extern unsigned char background_3[];

/* End of BACKGROUNDTHREE.H */
